### PR TITLE
Upload auto queue runs option

### PR DESCRIPTION
**Pull request by kyr-jle**
Hello, this PR is for adding the '-auto-queue-runs' option for tfci upload . AutoQueueRuns default as false in order to avoid breaking changes (contrary to API doc which defaults at true)

## Description

We are transitioning from VCS workflow and need to keep that functionnality. It's nicer to use tfci that curl.

### CODE REVIEW

**Comment by mjyocca** [comment]
@kyr-jle Thank you for opening this pull request. Just out of curiosity, what particular workflows / use cases would this enable for you?

**Comment by kyr-jle** [comment]
@mjyocca  :  Majority of our workspaces are currently using VCS workflow  and the aim is to migrate to API workflow in order to enable some more complex use-cases (then for API workflow to become the new default ) . The main goal is to easily be able to mimic the VCS workflow feature which allows to queue non speculative runs waiting for apply which is enabled by default in API, but disabled in tfci without a possibility to turn it back on(that is an undesired  breaking change for us). In our case, PR approvers are not necessarily the exact same people reviewing terraform plan apply, and we do not want to block merge (we have some monorepo structures hosting many workspaces where it would be impractical). It's also the default configuration when working with tfc/tfe so when transiting from VCS to API workflow the idea is to be able to propose to the teams an API workflow with the same behaviour as VCS workflow to start with, so it can be built upon it with confidence without modifying people workflow too much.

**Comment by aaabdelgany** [comment]
@kyr-jle We are not going to proceed with this approach for now. We've currently experimenting with a different approach to allow for queuing and monitoring non-speculative runs more easily and that will hopefully go out in a future release. We will link that new PR to this one to allow you to keep an eye on it once it's up for review.

**Comment by kyr-jle** [comment]
Hello @aaabdelgany , thanks for the update !

**Pull request closed without merging**
